---
- name: Install Amazon Corretto 8
  hosts: localhost
  become: yes

  vars:
    corretto_version: "8.402.08.1"
    corretto_install_dir: "/opt/amazon-corretto-{{ corretto_version }}"
    corretto_archive_url: "https://corretto.aws/downloads/resources/{{ corretto_version }}/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"

  tasks:
    - name: get the username running the deploy
      become: false
      shell: "/bin/bash -c 'whoami'"
      register: host_username

    - name: Display Command Output
      debug:
        var: host_username.stdout

    - name: Create Corretto installation directory
      ansible.builtin.file:
        path: "{{ corretto_install_dir }}"
        state: directory
        owner: "{{ host_username.stdout }}"
        group: "{{ host_username.stdout }}"
        mode: "0755"

    - name: Download Corretto tar.gz archive
      ansible.builtin.get_url:
        url: "{{ corretto_archive_url }}"
        dest: "/tmp/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"

    - name: Extract Corretto archive
      ansible.builtin.unarchive:
        src: "/tmp/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"
        dest: "{{ corretto_install_dir }}"
        remote_src: yes
        creates: "{{ corretto_install_dir }}/bin/java"
