- name: Nexus Installation
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
  roles:
    - role: rhattox.java_installation.java
      vars:
        java_version: 17
    - nexus
