- name: Nexus Installation
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    corretto_home_path: "/usr/lib/jvm/corretto"
    corretto_version: "8.402.08.1"

  roles:
    - java
    - nexus
