- name: Nexus Installation
  hosts: localhost
  become: true
  gather_facts: true
  collections:
    - rhattox.java_installation
  vars:
    ansible_python_interpreter: /opt/ansible-venv/bin/python
  roles:
    - role: java
      vars:
        java_version: 17
    # - nexus
