- name: Pre Install
  ansible.builtin.include_tasks: pre_install.yaml

- name: Core Install
  ansible.builtin.include_tasks: core_install.yaml

- name: Post Install
  ansible.builtin.include_tasks: post_install.yaml

# - name: Nginx Install
#   ansible.builtin.include_tasks: nginx_configuration.yaml
