---
- name: Install Amazon Corretto 8
  hosts: localhost
  become: true

  vars:
    correto_home_path: "/usr/lib/jvm"
    corretto_version: "8.402.08.1"
    corretto_install_dir: "/opt/amazon-corretto-{{ corretto_version }}"
    corretto_archive_url: "https://corretto.aws/downloads/resources/{{ corretto_version }}/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"

  tasks:
    - name: Retrieve system environment
      block:
        - name: Get the username running the deploy
          become: false
          register: host_username
          changed_when: host_username.rc != 0
          ansible.builtin.command: whoami

        - name: Display Command Output
          ansible.builtin.debug:
            var: host_username.stdout

    - name: Create Corretto installation directory
      ansible.builtin.file:
        path: "{{ corretto_install_dir }}"
        state: directory
        owner: "{{ host_username.stdout }}"
        group: "{{ host_username.stdout }}"
        mode: "0755"

    - name: Download Corretto tar.gz archive
      ansible.builtin.get_url:
        url: "{{ corretto_archive_url }}"
        dest: "/tmp/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"
        mode: "0755"

    - name: Extract Corretto archive
      ansible.builtin.unarchive:
        src: "/tmp/amazon-corretto-{{ corretto_version }}-linux-x64.tar.gz"
        dest: "{{ corretto_install_dir }}"
        remote_src: true
        creates: "{{ corretto_install_dir }}/bin/java"

    - name: Remove temporary file
      ansible.builtin.file:
        path: "{{ corretto_install_dir }}"
        state: absent
