app_name: nexus
app_home: "/var/lib/nexus"

app_version: "3.71.0-06"
app_tmp_path: "/tmp/nexus"
app_archive_url: "https://download.sonatype.com/nexus/3/nexus-{{ app_version }}-unix.tar.gz"
app_tmp_file: "/tmp/nexus.tar.gz"

corretto_home_path: "/usr/lib/jvm/corretto"
corretto_version: "17.0.13.11.1"
